# Generated by Django 4.1.4 on 2022-12-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
