# Generated by Django 4.1.4 on 2023-01-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_alter_movies_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
