# Generated by Django 4.1.4 on 2023-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_movies_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='peoples')),
            ],
        ),
    ]
