# Generated by Django 4.1.4 on 2023-01-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='filmapp.people'),
        ),
    ]
