# Generated by Django 4.1.4 on 2023-01-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmapp', '0007_delete_movies_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='peoples')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('released_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=10)),
                ('review', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('actors', models.ManyToManyField(to='filmapp.people')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
