# Generated by Django 4.1.4 on 2023-01-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='producer',
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.ManyToManyField(related_name='directors_info', to='filmapp.people'),
        ),
        migrations.AddField(
            model_name='movies',
            name='producer',
            field=models.ManyToManyField(related_name='producers_info', to='filmapp.people'),
        ),
    ]
