# Generated by Django 4.1.4 on 2023-01-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0010_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_user',
            name='otp',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
